name: Build HydroForge Editor

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build-windows:

    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Editor/requirements.txt

      - name: Build Editor
        run: |
          pyinstaller ^
            --noconfirm ^
            --clean ^
            --windowed ^
            --name HydroForge ^
            --icon editor/assets/HydroForge.ico ^
            editor/main.py
            
      - name: Copy Editor files
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path dist/HydroForge/Editor
          Copy-Item Editor/app.py dist/HydroForge/Editor/
          Copy-Item Editor/build_manager.py dist/HydroForge/Editor/

      - name: Upload HydroForge Editor
        uses: actions/upload-artifact@v4
        with:
          name: HydroForge-Windows
          path: dist/HydroForge/
