name: Build HydroForge Editor

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          pip install -r Editor/requirements.txt

      - name: Check PySide6
        shell: pwsh
        run: |
          python -c "import PySide6; print(PySide6.__version__)"

      - name: Build HydroForge Editor
        shell: pwsh
        run: |
          pyinstaller `
            --noconfirm `
            --clean `
            --windowed `
            --name HydroForge `
            --collect-all PySide6 `
            --icon "Editor/assets/HydroForge.ico" `
            "Editor/main.py"

      - name: Upload HydroForge
        uses: actions/upload-artifact@v4
        with:
          name: HydroForge-Windows
          path: dist/HydroForge/
